# Generated by Django 4.1.7 on 2023-04-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('investor', '0002_investing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investing',
            name='project',
        ),
        migrations.AddField(
            model_name='investing',
            name='project',
            field=models.ManyToManyField(to='project.project'),
        ),
    ]
