# Generated by Django 4.1.7 on 2023-04-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0003_remove_investing_project_investing_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investing',
            name='project',
        ),
        migrations.AddField(
            model_name='investing',
            name='project',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
