# Generated by Django 4.0 on 2023-04-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('TEC', 'Tecnología'), ('SCI', 'Ciencia'), ('ART', 'Arte'), ('REA', 'Lectura'), ('HEA', 'Salud'), ('MUS', 'Música')], default=0, max_length=3),
            preserve_default=False,
        ),
    ]
