# Generated by Django 4.0 on 2023-03-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectowner', '0001_initial'),
        ('project', '0002_alter_project_options_remove_project_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user_investor',
        ),
        migrations.AlterField(
            model_name='project',
            name='user_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectowner.projectowner'),
            preserve_default=False,
        ),
    ]
